model_list:
  - model_name: ollama/qwen2.5:1.5b
    litellm_params:
      base_url: http://10.1.1.47:11434

genre: literary_fiction # Default genre selection
prompts_file: config/prompts.yaml # Path to the prompts configuration file